### ISSUE TITLE
NatsError when connecting to Nats instances in Kubernetes

### ISSUE THREAD

**Issue by Iaskebba** [esatterwhite/skyring#20]
While booting up the ring node I am receiving this error.

2018-11-15T22:35:40.275Z skyring:nats creating nats client { servers: [ 'nats://10.28.0.105:4222' ] }
nats error { NatsError: Could not connect to server: Error: connect ECONNREFUSED 10.28.0.105:4222
    at Socket.<anonymous> (/opt/skyring/node_modules/nats/lib/nats.js:513:34)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'NatsError',
  message: 'Could not connect to server: Error: connect ECONNREFUSED 10.28.0.105:4222',
  code: 'CONN_ERR',
  chainedError:
   { Error: connect ECONNREFUSED 10.28.0.105:4222
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '10.28.0.105',
     port: 4222 } }
2018-11-15T22:35:40.309Z skyring:store storage backend ready { backend: 'leveldown',
  path: '/var/data/skyring',
  createIfMissing: true,
  errorIfExists: false }

The nat works properly under this ip and I can exec into a separate pod and connect to the nat using CLI tools. I believe that it is a problem with the wrapper for the nat.js but I am having trouble finding the exact issue.

**Comment by esatterwhite** [comment]
Hmm, well you got ECONNREFUSED, not EHOSTUNREACH. So it looks like node was able to contact the ip. The connection was refused. 

Are all of the things starting at the same time? Maybe the Skyring nodes are up before nats?

**Comment by Iaskebba** [comment]
The actual error was from our Istio service mesh. Nats did not like having envoy in between it and the skyring nodes. Once I ran it without the envoy sidecar everything worked great! Thank you!

**Comment by esatterwhite** [comment]
That is interesting. envoy is just a proxy, yes?  I wonder if it is something with the nats protocol and its own internal discovery. It might be worth opening an issue with nats and see if they are aware of it. 

I've been meaning to jump in w/ k8s and get some sensible default deployment set up for skyring or at least an example deployment.  Would you be interested in sharing or contributing an example back to the project?

**Comment by Iaskebba** [comment]
https://github.com/esatterwhite/skyring/pull/21
