### ISSUE TITLE
Can not start the cluster using docker compose

### ISSUE THREAD

**Issue by reubensjohn** [esatterwhite/skyring#64]
I am running the MongoDB example with docker compose. I can not get the nodes up and running. the nodes exits with the following ERROR.
```
keef:conf unable to load /opt/skyring configuration: Cannot find module '/opt/skyring/conf'
```
I dont see an 'opt' folder in github. Am I missing something

stack trace
```
node-2_1  | 2020-08-07T08:49:52.352Z keef:conf project root set to /opt/skyring
node-2_1  | 2020-08-07T08:49:52.353Z keef:conf package path set to /opt/skyring/packages
node-2_1  | 2020-08-07T08:49:52.364Z keef:conf loading config file `nenv`: /opt/skyring/z-skyring.development.json
node-2_1  | 2020-08-07T08:49:52.384Z keef:conf loading config file `project`: /opt/skyring/z-skyring.json
node-2_1  | 2020-08-07T08:49:52.385Z keef:conf loading config file `home`: /root/.config/z-skyring.json
node-2_1  | 2020-08-07T08:49:52.386Z keef:conf loading config file `etc`: /etc/z-skyring.json
node-2_1  | 2020-08-07T08:49:52.387Z keef:conf setting config defaults
node-2_1  | 2020-08-07T08:49:52.387Z keef:conf configuration modules /opt/skyring
node-2_1  | 2020-08-07T08:49:52.388Z keef:conf unable to load /opt/skyring configuration: Cannot find module '/opt/skyring/conf'
node-2_1  | Require stack:
node-2_1  | - /opt/skyring/node_modules/keef/index.js
node-2_1  | - /opt/skyring/node_modules/skyring/conf/index.js
node-2_1  | - /opt/skyring/node_modules/skyring/index.js
node-2_1  | - /opt/skyring/index.js
node-2_1  | 2020-08-07T08:49:52.388Z keef:conf etcd config:  undefined
node-2_1  | internal/modules/cjs/loader.js:1188
node-2_1  |   return process.dlopen(module, path.toNamespacedPath(filename));
node-2_1  |                  ^
node-2_1  | 
node-2_1  | Error: /opt/skyring/node_modules/farmhash/build/Release/farmhash.node: invalid ELF header
node-2_1  |     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
node-2_1  |     at Module.load (internal/modules/cjs/loader.js:986:32)
node-2_1  |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
node-2_1  |     at Module.require (internal/modules/cjs/loader.js:1026:19)
node-2_1  |     at require (internal/modules/cjs/helpers.js:72:18)
node-2_1  |     at Object.<anonymous> (/opt/skyring/node_modules/farmhash/index.js:3:18)
node-2_1  |     at Module._compile (internal/modules/cjs/loader.js:1138:30)
node-2_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
node-2_1  |     at Module.load (internal/modules/cjs/loader.js:986:32)
node-2_1  |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
```

**Comment by esatterwhite** [comment]
@reubensjohn opt is just the directory where the code is placed in the docker file. I had done some restructuring of the project. recently - I may have broken the compose setup. I will get this sorted out in the next day or two.

**Comment by esatterwhite** [comment]
@reubensjohn The mongo example started for me how did you try to run it?

**Comment by reubensjohn** [comment]
@esatterwhite I got it working. I had to make some changes in the docker compose and Dockerfile. Its all good now
